export enum MetricEnum {
	OS_FAILURES = 'osFailures',
	APP_FAILURES = 'appFailures',
	AGE = 'age',
	RAM_UTIL = 'ramUtil',
	CPU_UTIL = 'cpuUtil',
	RAM = 'ram',
	BATTERY_RUNTIME = 'batteryRuntime',
	BATTERY_HEALTH = 'batteryHealth',
	STORAGE_REMAINING = 'storageRemaining',
	HEALTH_SCORE = 'healthScore',
	SERVICE_TAG = 'serviceTag',
	HOST_NAME = 'hostName',
	ASSET_TAG = 'assetTag',
	MODEL = 'model',
	SUPPORT_LEVEL = 'supportLevel',
}
